### ISSUE TITLE
State and Nonce

### ISSUE THREAD

**Issue by vitorcarareto** [impak-finance/django-oidc-rp#4]
Hello,
I'm trying to use this package on my django app to signin users registered on another django app. (SSO)
I can successfully login to that django app, and it returns the callback at the url /oidc/auth/cb/?code=.....&state=.....
But when it calls the oidc_rp/views.py/OIDCAuthCallbackView class, the get method, these 2 lines return None, so It redirects to failure... 
```
state = request.session.get('oidc_auth_state', None)
nonce = request.session.pop('oidc_auth_nonce', None)
```

I have no clue why it is None, if it is something I configured wrong on the RP or the OP...

**Comment by ellmetha** [comment]
Well if your provider doesn't support nonces, you can set the `OIDC_RP_USE_NONCE` setting to `False`. Otherwise the callback will always try to verify the nonce before authenticating the user (if the nonce is not there the authentication flow will result in a failure).

The state value is a recommended one. Your OP should return it. 😉 

```
state
RECOMMENDED. Opaque value used to maintain state between the request and the callback. Typically, Cross-Site Request Forgery (CSRF, XSRF) mitigation is done by cryptographically binding the value of this parameter with a browser cookie. 
```

That said a setting could be introduced to disable the use of state values (not sure if this would be a good thing though).

**Comment by KDenisNoah** [comment]
> Hello,
> I'm trying to use this package on my django app to signin users registered on another django app. (SSO)
> I can successfully login to that django app, and it returns the callback at the url /oidc/auth/cb/?code=.....&state=.....
> But when it calls the oidc_rp/views.py/OIDCAuthCallbackView class, the get method, these 2 lines return None, so It redirects to failure...
> 
> ```
> state = request.session.get('oidc_auth_state', None)
> nonce = request.session.pop('oidc_auth_nonce', None)
> ```
> I have no clue why it is None, if it is something I configured wrong on the RP or the OP...

Hi did finally figure this out? I  have the same problem here and can't figure away to  resolve it 

Noah
